### ISSUE TITLE
MudBlazor app with LiveSharp 1.6.31 throws at LoadTypesFromAssembly

### ISSUE THREAD

**Issue by ChristianWeyer** [OYIon/LiveSharp#103]
server: 1.6.7.0
nuget: 1.6.31

Hi :-)

I created a new, almost blank, app with MudBlazor.
When running it with LiveSharp I get this error:

<img width="767" alt="Screen Shot 2020-11-22 at 12 15 11" src="https://user-images.githubusercontent.com/888718/99902513-a34be300-2cbe-11eb-8b72-28dc9e9f0a59.png">

Here is the repro:
https://github.com/thinktecture/blazor-wasm-mudblazor-demo

Thanks!

**Comment by ionoy** [comment]
This should be fixed in 1.6.33
