### ISSUE TITLE
How to apply license to LiveSharp?

### ISSUE THREAD

**Issue by hiredgunhouse** [OYIon/LiveSharp#109]
I have bought monthly subscription but I have no idea how to apply that license to my local LiveSharp.
How can I do that?

**Comment by ionoy** [comment]
Hello @hiredgunhouse 

You should be able to use the email you have provided during the purchase to activate the license in the LiveSharp Dashboard.

**Comment by hiredgunhouse** [comment]
Hey @ionoy 

Yes I figured that out finally, but it would be nice to add a short description somewhere in FAQ or Docs section cause that's not very obvious. Thank you for this amazing tool, I'm just starting to learn what it can and cannot do for me in terms of ASP.NET Core and so far it seems that new controllers are not discovered and changes to Startup.cs are also not reloaded. Not a deal breaker cause mostly I will be working on business features behind controllers.
Again looks like you have done something amazing here, huge, huge thank you and keep up the great work!

**Comment by ionoy** [comment]
Thank you @hiredgunhouse 

I'll add some more info about the license. 

I think controller changes are possible with LiveSharp, that worked the last time I tested it. As for `Startup.cs`, it would require a whole application restart for changes to take effect. If you know how to do that properly, you can implement it in the livesharp.dashboard.cs file and/or tell me, and I'll create built-in support.

**Comment by hiredgunhouse** [comment]
@ionoy yes, I'm already getting some crazy cool ideas for LiveSharp.
Now, I'm re-thinking my whole development workflow to get the maximum benefit from it.
Also I can see a huge potential for it to become a real game changer for development productivity.

**Comment by hiredgunhouse** [comment]
I got a rudimentary solution for hot-reloading the "whole" ASP.NET Core when i.e. Startup.cs is changed. It's not something you can bake into LiveSharp but at least this can be turned into a recipe in the docs. I can put together a clean sample and send it to you if you are interested.

**Comment by ionoy** [comment]
@hiredgunhouse, by the way, if you are interested in actually baking it into LiveSharp or adding some other cool stuff, I could compensate you for the work. PM me on Gitter/Discord if interested.
