### ISSUE TITLE
Log files in the project directory are scanned - Crash

### ISSUE THREAD

**Issue by pwhsoft** [OYIon/LiveSharp#113]
Log files that are used at runtime are attempted to be read by livesharp before compilation. 
An exception is thrown because there is a lock on the log file. 
This causes livesharp to stop working. Include options to exclude such files from livesharp.

Maybe there should be a possibility to exclude such files. An example for this are *.gitignore files. I think this would fit perfectly for this purpose. For example "*.livesharpignore".

**Comment by ionoy** [comment]
You can now use `.livesharpignore` file to exclude your logs from updating. More info here: https://www.livesharp.net/help/
