### ISSUE TITLE
Warnings and errors on save show in windows on top of editor instead of in debug output and error list 

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#12]
VSIX: 1.0.31, NuGet: 1.0.45

When saving a file during debugging, serialization errors / warnings of methods in the file are shown in blue windows in the editor area. This can be visually disrupting. Better to use the standard VS mechanism for errors / warnings by writing to the output window and also to the error / warning list.

Implementation may need to host a listener in VS that the save process posts to; the listener can then write to both the output window and the error list.

The output window text could point devs to the error list (error list window is usually not open during debugging but can function well there). The error list can then facilitate navigating to source etc.

**Comment by VincentH-Net** [comment]
Using the error list will allow devs to suppress specific warnings without introducing a dependency on L# by using standard #pragma warning. 

Since it will be some time before L# supports all possible syntax, this will promote early adoption

**Comment by ionoy** [comment]
Fixed.
