### ISSUE TITLE
BuildAgent locks build process

### ISSUE THREAD

**Issue by vlkam** [OYIon/LiveSharp#22]
I have solution with 6 projects, 3 of them are Core projects (netstandard + iOs +Android) and 3 of them application projects (netstandard + iOs + Android)
When I build solution build process often interrupts with messages 

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3027	Could not copy "obj\Debug\netstandard2.0\CoreXF.dll" to "bin\Debug\netstandard2.0\CoreXF.dll". Exceeded retry count of 10. Failed. The file is locked by: "LiveSharp.BuildAgent (2740)"	CoreXF	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4187	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3021	Unable to copy file "obj\Debug\netstandard2.0\CoreXF.dll" to "bin\Debug\netstandard2.0\CoreXF.dll". The process cannot access the file 'bin\Debug\netstandard2.0\CoreXF.dll' because it is being used by another process.	CoreXF	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4187

**Comment by ionoy** [comment]
Hi @vlkam 

Is CoreXF the project in the same solution?

**Comment by vlkam** [comment]
Hi Mihhail !

Yes, it is. 
Application's project references to the Core project in the same solution

**Comment by ionoy** [comment]
Does it do that all the time or just occasionally?

**Comment by vlkam** [comment]
To be sure I have to do few tests
I'll test LiveSharp today and tomorrow

And by the way, thanks a lot for great LiveXAML, it's absolute life saver for Xamarin Forms

**Comment by vlkam** [comment]
Unfortunately, that issue is repeated every build

I have 6 project:
![image](https://user-images.githubusercontent.com/7336057/48052492-24f47500-e1b9-11e8-81c4-00aea7fc2736.png)

JCabinet project is referenced to CoreXF project

I added LiveSharp to JCabinet project then made changes in JCabinet project and it was successfully compiled.

But then I make changes in CoreXF and build process was broken with errors

Error	MSB3027	Could not copy "obj\Debug\netstandard2.0\CoreXF.dll" to "bin\Debug\netstandard2.0\CoreXF.dll". Exceeded retry count of 10. Failed. The file is locked by: "LiveSharp.BuildAgent (16848)"	CoreXF	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4187	

Error	MSB3021	Unable to copy file "obj\Debug\netstandard2.0\CoreXF.dll" to "bin\Debug\netstandard2.0\CoreXF.dll". The process cannot access the file 'bin\Debug\netstandard2.0\CoreXF.dll' because it is being used by another process.	CoreXF	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4187
