### ISSUE TITLE
Support Visual Studio for Mac

### ISSUE THREAD

**Issue by WouterStraver** [OYIon/LiveSharp#23]

**Comment by ionoy** [comment]
Yes, definitely. But I want to concentrate on core functionality at the moment.

**Comment by WouterStraver** [comment]
Nice, I will be looking forward to it :-)

**Comment by kentfonager** [comment]
Any progress on this? :-)

**Comment by ionoy** [comment]
LiveSharp doesn't require an IDE extension anymore and is distributed as an Electron application. It should support both Windows and Mac development environments. In fact, it doesn't matter what IDE you use (VS, VS4Mac, VSCode or even Notepad). As long as the application running was built on the same computer, LiveSharp will automatically pick that up. 

The download link can be found on LiveSharp Releases: https://github.com/OYIon/LiveSharp/releases

I have just published it, so to my knowledge, Mac version still doesn't work properly. But this will change with the next release which will come today or maybe tomorrow.

**Comment by nathanielcook** [comment]
Just tried it on Mac and am not seeing anything changing when I save a file. The application status says "Server: Started". And yes, I installed the NuGet and I see the livesharp.rules file was generated upon build.) I guess I need to wait for the next release?

**Comment by adamlepley** [comment]
Following up on this feature. I installed the Server and Nuget, and everything seems to be connected and communicating correctly but I'm not seeing in the app respond to updates. When I save a code file, I see that the server status shows "received {NameOfClass) .ctor" and server log shows it's sending the update. Also, my app's console shows "live runtime: received {NameOfClass} .ctor , which seems like all of the communication is successful, just nothing happens in the iOS simulator. Am I missing a step?

**Comment by ionoy** [comment]
What version of the NuGet package are you using? Please make sure to update it to the latest one. Also, are you using LiveSharp with Xamarin.Forms or some other platform?

**Comment by ionoy** [comment]
@nathanielcook Sorry for not responding earlier. Yes, you should probably try upgrading to the latest versions since there were a lot of changes.

**Comment by adamlepley** [comment]
> What version of the NuGet package are you using? Please make sure to update it to the latest one. Also, are you using LiveSharp with Xamarin.Forms or some other platform?
> 
> EDIT: Just saw the Twitter mention. You are probably trying LiveSharp for Coded UI. In this case, you should define a `Build` method and call it from the constructor. This way LiveSharp can call it on an existing page without instantiating a new one.
> 
> Something like this:
> 
> ```
> public class MyPage : Page
> {
>   public MyPage() => Build();
>   public Build() 
>   {
>     Content = new Label { Text = "Hello, World!" };
>   }
> }
> ```
> 
> Here is a concrete example: https://github.com/VincentH-Net/CSharpForMarkup/blob/master/Example/CSharpForMarkupExample/Views/Pages/RegistrationCodePage.cs

That resolved my issue @ionoy, Thanks!!! This is an amazing tool and love that you removed the dependency on the IDE. Well done!
