### ISSUE TITLE
error installing nuget

### ISSUE THREAD

**Issue by egarim** [OYIon/LiveSharp#25]
It does not matter what version of the nuget I try to install I always get this error
   Error	NU1108	Cycle detected. 
  LiveSharp -> LiveSharp.Support.XamarinForms 1.0.51 -> LiveSharp (>= 1.0.51).	LiveSharp

I'm using xamarin forms version 3.4.0.1008975

**Comment by ionoy** [comment]
Oh, you don't need the Support NuGet anymore. I should unlist it, thanks!
