### ISSUE TITLE
SYNTAX: ctor with optional arguments gives exception when parentheses are omitted

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#27]
E.g. when a view ctor has signature:
`public XEntry(bool thinStyle = false, bool autoCancel = false, bool noRightView = false)`

And the page build method contains:
`new XEntry () { }`
then LiveSharp updates without error on save.

However when the ctor arguments parentheses are omitted, an exception occurs on save:
`new XEntry { }`

> LiveSharp.VisualStudio.Serialization.ETSerializationException: Serialization failed for: 
new XEntry { }
Block --> {...
 ExpressionStatement --> Content = new KeyboardAccessoryLayout {...
  SimpleAssignmentExpression --> Content = new KeyboardAccessoryLayout {...
   InvocationExpression --> new KeyboardAccessoryLayout {...
    ObjectCreationExpression --> new KeyboardAccessoryLayout {...
     ObjectCreationExpression --> new Grid {...
      InvocationExpression --> new ScrollView { Content = new Grid {...
       ObjectCreationExpression --> new ScrollView { Content = new Grid {...
        ObjectCreationExpression --> new Grid {...
         InvocationExpression --> // Hidden debug buttons:...
          InvocationExpression --> // Hidden debug buttons:...
           InvocationExpression --> // Hidden debug buttons:...
            InvocationExpression --> // Hidden debug buttons:...
             ObjectCreationExpression --> // Hidden debug buttons:...
              ObjectCreationExpression --> new XEntry { } ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.ObjectCreationExpression(ObjectCreationExpressionSyntax objectCreationExpressionSyntax, ConversionContext conversionContext) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.Handlers.cs:line 186

**Comment by ionoy** [comment]
fixed in the next release
