### ISSUE TITLE
DeserializationException when adding constant and field

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#36]
Server 0.9.9, NuGet 1.1.11
Repro: 
https://github.com/VincentH-Net/CSharpForMarkup/blob/livesharp-issues/Example/CSharpForMarkupExample/Views/IssuePages/AddConstantAndField.cs

**Comment by ionoy** [comment]
Feels like `left: PageMarginSize + aConstant` is the reason. I'll take a look tomorrow.

Thanks!

**Comment by VincentH-Net** [comment]
Verified fixed in LiveSharp server 0.9.10 and NuGet 1.1.13
