### ISSUE TITLE
DeserializationException when assigning scrollview content in separate build method

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#37]
Server 0.9.9, NuGet 1.1.11

livesharp.rules file contains line `CSharpForMarkupExample.Views.* Build*`

Repro:
https://github.com/VincentH-Net/CSharpForMarkup/blob/livesharp-issues/Example/CSharpForMarkupExample/Views/IssuePages/BuildViewContentInSeparateMethod.cs

**Comment by ionoy** [comment]
Thanks!

**Comment by VincentH-Net** [comment]
Verified fixed in LiveSharp server 0.9.10 and NuGet 1.1.13
