### ISSUE TITLE
No response on save when source contains null-conditional operator

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#4]
`new WebView { Source = htmlWebViewSource = new HtmlWebViewSource { Html = vm?.BodyHtml?.Replace(Case.HtmlFontFamilyPlaceholder, fontFamily) } }`

The null-conditional operator seems the cause because this works:
`Source = htmlWebViewSource = new HtmlWebViewSource { Html = vm.BodyHtml.Replace(Case.HtmlFontFamilyPlaceholder, fontFamily) },`

**Comment by ionoy** [comment]
Should be fixed in 1.0.24
