### ISSUE TITLE
Hidden exception stops LiveSharp processing

### ISSUE THREAD

**Issue by lhughey** [OYIon/LiveSharp#45]
LiveSharp is not processing c# or Xaml changes after passing a page which seems have thrown a caught exception. The LiveSharp inspector is showing that there was an error on a page 2 pages back from where I'm now trying to view Xaml or C# changes. 

The info I'm getting from the Inspector's Viewmodel screen is below. The Inspector's debugger is not displaying any data.

 **Inspector's Viewmodel Output** 
`SubViewModels	System.Collections.Generic.List`1[Mobile.Core.ViewModel.ITabViewModel]
Title	" TitleOFPage"
PatientTitle	
IsBusy	False
PageType	Normal
Changing System.Reactive.Linq.ObservableImpl.Cast`2[System.Object,ReactiveUI.IReactivePropertyChangedEventArgs`1[ReactiveUI.IReactiveObject]]
Changed	System.Reactive.Linq.ObservableImpl.Cast`2[System.Object,ReactiveUI.IReactivePropertyChangedEventArgs`1[ReactiveUI.IReactiveObject]]
ThrownExceptions	ReactiveUI.ScheduledSubject`1[System.Exception]`

**What I'm expecting**
I am expecting LiveSharp to fail to process on a page that has a thrown exception, but attempt to process on the next page. If the next page exhibits an exception, it details should be added to the a log. 

**Note**
'll see what I can do to reproduce this. I'm dealing with a complicated codebase but have used LiveXaml on it for 6 months and LiveSharp a few here and there (mostly for Xaml changes).

**Comment by ionoy** [comment]
Thanks for the report @lhughey!

Is there anything posted in the Log panel when you these update attempts fail?
Also, what is the log output for the initial exception?

**Comment by lhughey** [comment]
There is nothing in the debug log of the app in Visual studio because the error doesn't bubble up. It seems be captured in the Reactive code but is observed by LiveSharp.

Also, XAML changes are not processed, I lightly mentioned it before, but wasn't very clear.

**You can see the Inspector output at**
 http://imgur.com/a/OGscMX4

**Here is the LiveSharp log**

- 08:06:39 Starting LiveServer
08:06:39 listening on port 50540 starting
08:06:39 listening on port 50540 started
08:06:40 License is valid until 1/1/2021
08:06:40 Latest available NuGet package version: 1.1.20
08:25:42 client connected: 10.211.55.2:58475
08:25:44 Client 10.211.55.2:58475 joined group 1
08:25:44 Client 10.211.55.2:58475 joined group 4
08:25:44 Application NuGet package version: 1.1.20
08:25:46 Workspace loading finished in 1436ms
08:25:46 directory: C:\Source\xxx\Solutions
08:25:46 watcher started for *.cs at C:\Source\xxx\Solutions
08:25:46 watcher started for *.xaml at C:\Source\xxx\Solutions
08:25:46 watcher started for *.csproj at C:\Source\xxx\Solutions
08:25:46 watcher started for C:\Source\xxx\Solutions\TC_EPMobile.iOS.sln at C:\Source\xxx\Solutions
08:25:46 Starting job: Dry run for xxx.Core
08:25:47 Ended job: Dry run for xxx.Core (966)
08:44:33 client disconnected: 10.211.55.2:58475
09:38:46 client connected: 10.211.55.2:59797
09:38:48 Client 10.211.55.2:59797 joined group 1
09:38:48 Client 10.211.55.2:59797 joined group 4

**Comment by lhughey** [comment]
Note: This project works fine with LiveXaml (changes to xaml are displayed).

**Comment by ionoy** [comment]
Do you see any messages appearing in the application log (Status tab)? I'm trying to understand if the issue is with the communication or the update itself.

Thanks!

**Comment by lhughey** [comment]
Sorry for the late reply. I've pasted the log of the status tab (of LiveSharp server) above in the previous post. 

If you'd like, we can do a screen share on skype or something. I hate not being able to reproduce this but want you to be able to see what is going on (or at least see a lack of details so more verbosity can be displayed for additional debugging). My timezone is UTC -6. Let me know if that would help.

**Comment by lhughey** [comment]
This was resolved with the latest nuget release (1.1.22). Thanks!

**Comment by ionoy** [comment]
Awesome!
