### ISSUE TITLE
Does it support Blazor ?

### ISSUE THREAD

**Issue by aammfe** [OYIon/LiveSharp#49]

**Comment by ionoy** [comment]
Hello @aammfe 

Are you talking about server-side Blazor or the WebAssembly one? Are you interested in page hot-reload?

**Comment by aammfe** [comment]
**WebAssembly**  

> Are you interested in page hot-reload?

yes

**Comment by ionoy** [comment]
I've investigated the issue a little bit more, and it definitely needs some development. I'm interested in making Blazor work, so the issue will stay open until I have more info.

**Comment by ionoy** [comment]
Hello @aammfe 

LiveSharp (>=1.1.56) supports server-side Blazor hot reload now.

**Comment by dominiclapointe** [comment]
Is it still on your todo list to have Blazor WASM (webAssembly) or you will only go for Blazor serverside?

Thank you

**Comment by ionoy** [comment]
Yes, Blazor WASM support will be added in a few days.

**Comment by ionoy** [comment]
I have finally published preview versions of the new LiveSharp. You can use the following links to try it. Both Blazor WASM and Server-side should be supported.

Server: https://github.com/OYIon/LiveSharp/releases/tag/1.5-beta
NuGet: https://www.nuget.org/packages/LiveSharp/1.5.6-beta
