### ISSUE TITLE
Server stuck monitoring same solution regardless of solution loaded in VS

### ISSUE THREAD

**Issue by lhughey** [OYIon/LiveSharp#50]
The server wont refresh the monitored solution. It is stuck monitoring a solution that is not loaded in VS. 
Of note: The solution that is being monitored in LiveSharp has an out of date Nuget package. See image [here](https://imgur.com/ewG2JCh)

using:
LiveSharp 1.1.25
Server v.13

Things I've tried:
Restarted LiveSharp server multiple times
Cleaned obj/bin folders of app
Restarted VS
Multiple combinations of restarting LiveSharp server and VS.

Things I'll try:
1. Removing LiveSharp from the Solution that Livesharp is currently monitoring. This solution is not loaded into VS.
2. Uninstalling/Reinstalling LiveSharp server.

**Comment by lhughey** [comment]
Update: Updating the nuget in the previously loaded solution resolved the problem. The server is now able to watch the newly loaded solution.

**Comment by lhughey** [comment]
Update: I'm not sure if this is related, but this I noticed that VS monitoring a git location what is not open or related to the solution loaded. This is the same solution that LiveSharp was stuck monitoring. I'll remove the git integration from VS and continue using an external git gui (GitKraken).

I'm using VS 16.4.3 for Windows.

**Comment by ionoy** [comment]
Thanks for the follow-up

Well, LiveSharp uses Roslyn to load the solution. I don't think there is any connection with git. Although it might be something to do with your particular filesystem. 

Please tell me if this happens again. I'm closing the issue for now.
