### ISSUE TITLE
Duplicate error with Xaml changes in referenced projects

### ISSUE THREAD

**Issue by lhughey** [OYIon/LiveSharp#51]
Using:
Server 0.9.13
Nuget v1.1.25

I have a XF project that has helper projects that are not included within the watch directory, but have references shared into into the project at the watch directory. 

[Please see here for an illustration of the watch directory](https://imgur.com/d1m9QdY)

The folder with the green highlighting is the "main" netstandard projec.  The red highlighted project is referenced in the green folder. I am changing a XAML file in the red project and getting the following error in the popup of the app when doing "An element with the the name "frameUser" already exists in this Namescope. 

The element frameUser exists in the LoginPage.xaml page in the referenced project (not within the watch directory) but referenced by the project in the watch directory. Put another way, the page that is being changed is located in the red highlighted netstandard project.

The only error I see in the log file is:
09:23:49 Error: GetPropertiesForFile couldn't find file: C:\Source\XXXXXn\XXXXan.Benefits\src\XXXXan.Benefits.AA\Views\LoginPage.xaml

The details of the log file are below. Please check out the 3rd and 4th lines of the log.

- 09:22:53 Starting job: Dry run for XXXXXn.Benefits
- 09:22:53 Ended job: Dry run for XXXXXn.Benefits (37)
- 09:23:49 Starting job: Handling XAML update: Views\LoginPage.xaml
- 09:23:49 Error: GetPropertiesForFile couldn't find file: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\Views\LoginPage.xaml
- 09:23:49 Document saved C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\Views\LoginPage.xaml
- 09:23:49 Ended job: Handling XAML update: Views\LoginPage.xaml (11)
- 09:23:49 Warning: Can't find document for C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\Views\LoginPage.xaml
- 09:23:50 Starting job: Handling C# update: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\obj\Debug\netstandard2.0\Views\InternalPolicyWebviewPage.xaml.g.cs
- 09:23:50 Sending type XXXXXn.Benefits.AA.Views.InternalPolicyWebviewPage
- 09:23:50 Ended job: Handling C# update: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\obj\Debug\netstandard2.0\Views\InternalPolicyWebviewPage.xaml.g.cs (128)
- 09:23:50 Starting job: Handling C# update: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\obj\Debug\netstandard2.0\Views\LoginPage.xaml.g.cs
- 09:23:50 Sending type XXXXXn.Benefits.AA.Views.LoginPage
- 09:23:50 Ended job: Handling C# update: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\obj\Debug\netstandard2.0\Views\LoginPage.xaml.g.cs (43)
- 09:23:50 Starting job: Handling C# update: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\obj\Debug\netstandard2.0\Views\LoginWebViewPage.xaml.g.cs
- 09:23:50 Sending type XXXXXn.Benefits.AA.Views.LoginWebViewPage
- 09:23:50 Ended job: Handling C# update: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\obj\Debug\netstandard2.0\Views\LoginWebViewPage.xaml.g.cs (31)
- 09:23:50 Starting job: Handling C# update: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\obj\Debug\netstandard2.0\Views\MaintenancePage.xaml.g.cs
- 09:23:50 Sending type XXXXXn.Benefits.AA.Views.MaintenancePage
- 09:23:50 Ended job: Handling C# update: C:\Source\XXXXXn\src\XXXXXn.Benefits.AA\obj\Debug\netstandard2.0\Views\MaintenancePage.xaml.g.cs (49)

**Comment by ionoy** [comment]
Thanks, I'll take a look

**Comment by ionoy** [comment]
Can you try with the attached NuGet package?

https://1drv.ms/u/s!ApDBNJZql1r7jfoTz3LxWgCTjJv11g?e=Hh6rzO

**Comment by lhughey** [comment]
i'm still getting the same error with the nuget you posted above. I really do think it is related to the two folders being watched as displayed below from the log.

10:51:58 watcher created for at C:\Source\xxx.Benefits.AA\ --folder with xaml file being changed
10:51:58 watcher created for at C:\Source\xxx.Benefits\ . - main netstandard

**Comment by ionoy** [comment]
Thanks for the update!

Even though there are multiple watchers, it still sends the update only once. The previous log doesn't show duplicate handling of the same file. 

Do you still see `GetPropertiesForFile` error popping up? I also think it might be an unrelated issue with LiveXAML that you have encountered.

**Comment by ionoy** [comment]
This is now fixed, right?

**Comment by lhughey** [comment]
Yes, this issue seems to be fixed. Thanks!
