### ISSUE TITLE
Blazor Server: Adding elements to inline stylesheet causes failure

### ISSUE THREAD

**Issue by Simcon** [OYIon/LiveSharp#58]
If I add a section to an inline stylesheet while debugging with LiveSharp the app blows up with the attached error. 

eg. if I add the following element:

```
<style>

section {
}

</style>
```

This is a Blazor server-side app.

[livesharp_error.txt](https://github.com/OYIon/LiveSharp/files/4446026/livesharp_error.txt)

**Comment by Simcon** [comment]
Error not related to stylesheet.

**Comment by ionoy** [comment]
@Simcon It seems that LiveSharp fails to compile some `async/await` code. Do you have any async code in your Page?

**Comment by Simcon** [comment]
Yes - I override OnAfterRenderAsync

@code {

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JSRuntime.InvokeAsync<string>("index", null);
        }

        await base.OnAfterRenderAsync(firstRender);
    }
}

**Comment by ionoy** [comment]
This should be fixed now.
