### ISSUE TITLE
RUNTIME: Composing markup top-down by calling other build methods from BuildContent is not supported OOB

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#6]
When you move part of the markup in `BuildContent` to separate methods on the page, and then call those methods from `BuildContent` like so:
```C#
View BuildContent() => new StackLayout { Children = {
      Header(),
      Body(),
      Footer()
  }};

View Header() => new ...
View Body() => new ...
View Footer() => new ... 
```
and you change the markup in e.g. `Body` and save, the page is not updated with the changes.

Being able to compose markup top-down so it reads like a story is a great benefit of coded UI, would be great if LiveSharp supports that. The alternative is a single BuildContent method with sometimes hundreds of lines of code.

Desired behavior: on save, when one or more methods on the page have been modified, the `BuildContent` method is called exactly one time and the page content is updated.

Note that this approach can also be used to **name areas**

**Comment by VincentH-Net** [comment]
VSIX: 1.0.31, NuGet: 1.0.45
Look like this is partially fixed:

E.g. when I have: 
```C#
public View BuildContent()
{
    //... new Grid { Children = {
        Timeline_BC(),
}

public View Timeline_BC()
{
    // ....
}
```

And I modify only markup in Timeline_BC() and save, the page does not update
But when I then modify some arkup in BuildContent and save, subsequent changes and saved to only TimeLine_BC does update the page.

**Comment by VincentH-Net** [comment]
A workaround that I use now is to compose with assignment methods, e.g.:
```C#
public class ProductsPage : ContentPage 
{
    ListView productsListView;

    public ProductsPage() => Build();

    void Build()
    {
        Content = new Grid { Children = {

            new ListView {
                // ...
            } .Assign (out productsListView),

        }};

        BuildProductTemplate();
    }

    void BuildProductTemplate()
    {
        productsListView.ItemTemplate  = new DataTemplate(() => new ViewCell { View = new Grid {
            // ...
        }});
    }

}
```
This has the added benefit that on save only the UI in the changed method is updated.

**Comment by ionoy** [comment]
I think the latest update handler should call the `Build` method. This method also needs to assign the `Content` by itself, so it can return `void`

```
internal class LiveSharpDefaultUpdateHandler
{
    private static WeakReference<object> _latestContentPage = new WeakReference<object>(null);

    public static void HandleCall(object instance, string methodIdentifier)
    {
        if (instance is ContentPage && methodIdentifier.EndsWith(" Build "))
            _latestContentPage.SetTarget(instance);
    }

    public static void HandleUpdate(Dictionary<string, IReadOnlyList<object>> updatedMethods)
    {
        var instances = updatedMethods.SelectMany(kvp => kvp.Value)
                                        .Where(i => i != null)
                                        .Distinct()
                                        .ToArray();

        Device.BeginInvokeOnMainThread(() => {
            var found = false;

            foreach (var instance in instances) {
                try {
                    if (CallBuildMethod(instance))
                        found = true;
                } catch (TargetInvocationException e) {
                    var inner = e.InnerException;
                    while (inner is TargetInvocationException tie)
                        inner = tie.InnerException;
                    if (inner != null)
                        throw inner;
                    throw;
                }
            }

            if (!found) {
                if (_latestContentPage.TryGetTarget(out var contentPage))
                    CallBuildMethod(contentPage);                    
            }
        });
    }

    private static bool CallBuildMethod(object instance)
    {
        var bindingFlags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;

        if (instance.GetType().GetMethod("Build", bindingFlags, null, new Type[] { }, null) is MethodInfo mi) {
            mi.Invoke(instance, null);
            return true;
        }

        return false;
    }
}
```

**Comment by VincentH-Net** [comment]
I use the assignment composition approach together with this line in the **livesharp.rules** file to invoke any method whose name starts with **Build** in my Pages namespace:
```MyApp.Pages.* Build*```

All Build* methods are parameterless and return void.

The approach I use works with the current version of LiveSharp, but does depend on livesharp.rules flexibility. The update handler code above does not seem to support that? 

I hope you are not planning on removing livesharp.rules support?

**Comment by ionoy** [comment]
Current update handler for XF calls `Build` method whenever any code change in the project occurs. This approach works well when you are developing view models, data templates or even services.

I think it should still support your scenario because you have a `Build` method.

**Comment by VincentH-Net** [comment]
You are correct, I created my above pattern for use with a very early alpha version of LiveSharp, but in the upcoming release you provided me this works just fine (tested in VS 2019 for Windows):
```C#
    public class MainPage : ContentPage
    {
        public MainPage() => Build();

        void Build()
        {
            Content = new StackLayout
            {
                Children =
                {
                    new Label { Text = "Hello World s" },
                    BuildLabel ("Label 2"),
                    BuildLabel ("Label 3"),
                    BuildLabel ("Label 4"),
                }
            };
        }

        Label BuildLabel(string text) => new Label { Text = text };
    }
```

When I change the `BuildLabel` method and save, the Build() method gets called.
No need to specify a `livesharp.rules` file.
Also works if I split the above file into 3 partial class files.

As far as I am concerned, this issue is resolved and can be closed 👍
