### ISSUE TITLE
LiverSharp Server 

### ISSUE THREAD

**Issue by timeshift92** [OYIon/LiveSharp#62]
![image](https://user-images.githubusercontent.com/13614530/80272873-cf7e9180-86e6-11ea-8ede-807d1eb5844a.png)
hello, i'm downloading this package LiveSharp-Server-0.9.13-mac.zip

![image](https://user-images.githubusercontent.com/13614530/80272902-0eace280-86e7-11ea-9274-16409650e94b.png)

**Comment by ionoy** [comment]
Hello @timeshift92 

It's possible that your privacy settings don't allow to open programs from unknown publishers. By the way, does the same happen if you install it from DMG?

**Comment by timeshift92** [comment]
Thank you, you were right, you had to run
such a team
`` ``
sudo spctl --master-disable
`` ``

**Comment by ionoy** [comment]
Thanks for providing more info!
