### ISSUE TITLE
[Feature Request] LiveSharp Server Dark Mode for macOS

### ISSUE THREAD

**Issue by mrlife** [OYIon/LiveSharp#64]
Possible to add support for dark mode?

Possible these could help:

https://www.electronjs.org/docs/tutorial/mojave-dark-mode-guide
https://medium.com/missive-app/make-your-electron-app-dark-mode-compatible-c23dcfdd0dfa

**Comment by ionoy** [comment]
Hi @mrlife

I actually thought about implementing a custom dark mode, so it would be cross-platform. The updated application should arrive sometime next week.
