### ISSUE TITLE
LiveSharp Server continues running after completely closing app

### ISSUE THREAD

**Issue by mrlife** [OYIon/LiveSharp#65]
On macOS, I noticed that the server was still running and working after completely closing out the app. Preferably. the server only runs when the server app is open.

**Comment by ionoy** [comment]
Hello @mrlife 

Could you try the newly uploaded beta version? This might resolve the issue.

Server: https://github.com/OYIon/LiveSharp/releases/tag/1.5-beta
NuGet: https://www.nuget.org/packages/LiveSharp/ (make sure to install prerelease version)

Thanks

**Comment by mrlife** [comment]
@ionoy Thanks, I haven't been able to reproduce with 0.9 or 1.5, so closing.
