### ISSUE TITLE
Blazor wasm support

### ISSUE THREAD

**Issue by dominiclapointe** [OYIon/LiveSharp#66]
Hi,

Is supporting hot reload for blazor wasm on your roadmap?

Thank you

**Comment by ionoy** [comment]
@dominiclapointe WASM support is coming this week. It's already working perfectly in my internal builds!

**Comment by dominiclapointe** [comment]
@ionoy Thats awesome, is there some preview i could try or need to wait the official release?

**Comment by valentasm1** [comment]
I assume with current release [v1.5.2](https://github.com/OYIon/LiveSharp/releases/tag/v1.5.2) it should work on webasembly.
Is it working only on Edge?

**Comment by ionoy** [comment]
@valentasm1 It should work in any browser. By the way, v1.5.2 is a "fake" release, so people would see the announcement about migration to the "dotnet tool". The tool itself is 1.6.0 at the moment.
