### ISSUE TITLE
Exception on save when code contains assignment to field on page

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#7]
`.Invoke(g => { scrollingGrid = g; })` , where `scrollingGrid` is a field on the page, gives:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Expression of type 'System.Func2[Xamarin.Forms.Grid,Xamarin.Forms.Grid]' cannot be used for parameter of type 'System.Action1[Xamarin.Forms.Grid]' of method 'Xamarin.Forms.Grid InvokeGrid'
Parameter name: arg1

**Comment by VincentH-Net** [comment]
A possible workaround is: `.Invoke(g => SetScrollingGrid(g))`

**Comment by ionoy** [comment]
Should be fixed in 1.0.24
