### ISSUE TITLE
Connection Exception because port numbers don't match

### ISSUE THREAD

**Issue by jh-webton** [OYIon/LiveSharp#71]
Using Visual Studio 2019 Community Edition with a Blazor project

Used ports by LiveSharp: 50540, 52540, 54540, 56540 & 58540
Userd port by de web application 44338 (ssl)

**Output**
livesharp: Connecting to 192.168.1.3:54540
livesharp: error: Connection exception: System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. 192.168.1.3:54540)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. 192.168.1.3:54540
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**URL of the web application**
https://localhost:44348

**Url in browser network tab**
https://localhost:44348/_blazor/negotiate?negotiateVersion=1

**Comment by ionoy** [comment]
Hello @jh-webton 

Thank you for the feedback!

Can you check the logs at `%TEMP%\LiveSharp\server-*.log`? It seems that there was an issue with server initialization.

**Comment by jh-webton** [comment]
Hello @ionoy ,

I checked the folder and it only contains buildtask-*.log like _buildtask-frc0hhl2.log_

The LiveServer screen looks like this
![image](https://user-images.githubusercontent.com/50216504/83887318-922b0c00-a748-11ea-8899-4fc6b425fd43.png)

**Comment by ionoy** [comment]
Can you try the new release https://github.com/OYIon/LiveSharp/releases/tag/v1.5.1

You'll also need to update the NuGet package.

**Comment by jh-webton** [comment]
@ionoy 

Great, the new release fixed my issue. Now I see text in the LiveSharp server and it works like I expected it to do.
