### ISSUE TITLE
TypeError: Canot read property 'loadUrl' of undefined

### ISSUE THREAD

**Issue by chrisofthecoffee** [OYIon/LiveSharp#72]
I'm trialling LiveSharp, installed yesterday and initially it seemed to work fine but today on first use (after reboot...) it's not rebuilding when I save my Xamarin project and I get the below error popup from the server window. 

(Just verified I do have the NuGet package installed... thought i didn't for a moment - it's installed in the shared project, not in the Android/IOS ones)

![image](https://user-images.githubusercontent.com/17450109/83867648-57cb6a00-a75c-11ea-995f-063752d1fcba.png)

3 log files created for this current run (build and deploy to Android emulator), first says;

18:41: Message: Loaded inject rule: *
18:41: Message: Loaded start method rule: <empty>
18:41: Message: Client Start method detected: System.Void [my application name]::.ctor()
18:41: Message: Client Start method detected: System.Void [my application name]::.cctor()
18:41: Message: Update handler: LiveSharp.XamarinFormsUpdateHandler
18:41: Message: Update handler: LiveSharp.XamarinFormsViewHandler
18:41: Message: Update handler: LiveSharp.XamarinFormsViewModelHandler
18:41: Warning: Injecting code into BindTap failed: Value cannot be null.
Parameter name: method

2nd says (partial log around same time)
18:41:44 Starting dashboard process with arguments: /electronPort=8000 /electronWebPort=8002 /SolutionPath="C:\Dev\[My Solution].sln" /ProjectName="[My project name]" /ProjectDir="C:\Dev\[My project directory]" /NuGetPackagePath="C:\Users\Chris\.nuget\packages\livesharp\1.5.21\build"
18:41:45 client connected: 127.0.0.1:53292
18:41:45 Client 127.0.0.1:53292 joined group 7
18:41:45 Client 127.0.0.1:53292 joined group 6

3rd says (partial log around same time)
18:41:48 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
18:41:48 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
18:41:48 The type or namespace name 'Debuggable' could not be found (are you missing a using directive or an assembly reference?)

...I'm assuming the last is talking about the LiveSharp server code, my app builds and works fine, just the LiveSharp logs have these errors.

Apologies for not asking in the gittable forum as suggested on the server window but on creating a user the OAuth message asked me to OK it having read access to 'team membership', 'private project boards' and 'private email addresses' - I'm not the owner of the project, not my place to give another company access to it's data so I couldn't create an account ans there's no 'register with an email address' option to gitter.

I've rebooted again and same message, rebuilt my project a few times, checked for NuGet updates and only installed LiveSharp yesterday so presumably have the latest version - as I say, it did seem to work yesterday in as much as I changed code and saved and the emulator updated - but it was very late, I kinda installed it, tried it, called it a good time to stop for he night and didn't look at it properly until today.

**Comment by chrisofthecoffee** [comment]
I just tried this with the CSharpForMarkupDemos solution that I was looking at yesterday and get the same 'A JavaScript error....' popup there too. Nothing untoward in the log for that run though, essentially all the success messages IO got when running my app, but without the ones about 'The type 'Object' is defined in an assembly that is not referenced' - but surely my app can find the definition of 'Object'... it's working fine ! - I'm still not clear whather it's complaining about my app or LiveSharp.

**Comment by ionoy** [comment]
Hello @chrisofthecoffee 

Thank you for the detailed feedback!

Is `The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.` message coming from `%TEMP%\server-*.log`?

Also, when does `loadURL` popup appear? Is it consistent?

Thanks,
Mihhail

**Comment by chrisofthecoffee** [comment]
A quick update, I ran for a couple of hours with no problems, LiveSharp updating many times with zero problems then the same message (below) popped up again. I wasn't doing anything special, hitting save after setting binding on an ActivityIndicator. No errors in any logs and the popup repeats on each start/deploy.

Closed the service and restarted, working fine again.

![image](https://user-images.githubusercontent.com/17450109/83909821-1064ce00-a79c-11ea-8106-51ff550e74e5.png)

**Comment by chrisofthecoffee** [comment]
I think this is two different problems, perhaps I should have logged them as discrete issues, this morning, first run from freshly booted machine gets the same messages below from the project that was being LiveSharped just fine last night, no JavaScript error popup.

10:31:49.280: Ended job: Dry run for RebreatherBookingsApp (2717)

10:31:49.279: FileSaved handler failed System.Exception: Serializing document failed at LiveSharp.VisualStudio.Services.DocumentSerializer..ctor(Project project, SyntaxNode documentRoot, SemanticModel semanticModel, ILogger logger, TypeRegistry typeRegistry, Func`2 typeFilter, Func`2 memberFilter) at LiveSharp.VisualStudio.Services.LiveSharpHandler.PrepareUpdatesAsync(Project project, SyntaxNode documentRoot, SemanticModel semanticModel, IReadOnlyList`1 updatedMethods, String documentName, Boolean isDryRun)

10:31:49.269: The type or namespace name 'Debuggable' could not be found (are you missing a using directive or an assembly reference?)

10:31:49.268: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

**Comment by ionoy** [comment]
There is a directory named `SolutionCache` in `.nuget\LiveSharp\[version]\build` It contains project information that LiveSharp uses for internal compilations. Please find the file named `[YourProjectName].info` and send it to me. Also, you can send it to my email (mihhail.maslakov at gmail dot com) or PM me on Gitter (https://gitter.im/LiveSharp/Lobby)

**Comment by chrisofthecoffee** [comment]
Thanks, am emailing diags to you now, unable to send to Gitter (see email).

**Comment by ionoy** [comment]
Could you try the attached NuGet package? I've updated the Roslyn dependencies, which is the most likely candidate to be the problem here. 

[LiveSharp.1.5.26.zip](https://github.com/OYIon/LiveSharp/files/4751122/LiveSharp.1.5.26.zip)

**Comment by chrisofthecoffee** [comment]
Trying to install with "Install-Package LiveSharp -Source d:\temp" gives the "The 'Source' parameter is not respected for the transitive package management based project(s)..." error (https://github.com/NuGet/Home/issues/7189) - have unzipped it to my visual studio offline packages directory and tried to install that way but it doesn't appear when I change source to search local folder... I've not done this before so I could well be missing something obvious...

In the meantime I notice there's a 1.5.25 on NuGet, I'll update to that and see if anything changes, doing that I notice I only have LiveSharp in my shared project, guess that's OK as it's working most of the time at least.

**Comment by chrisofthecoffee** [comment]
Hi, it's not working at all now, the logs pick up that source has changed bu the debugger window shows nothing happening. I've uninstalled server and package, restarted, reinstalled and same.

The logs windows shows;

**Comment by ionoy** [comment]
Please check if there is anything in the Output window after the update.

**Comment by chrisofthecoffee** [comment]
Ah, good call, didn't think to check there;

[0:] livesharp: error: System.Exception: MethodInfo not found Define (ValueTuple`2[])
  at LiveSharp.Runtime.IL.MethodMetadata.GetCompatibleMethod (System.Collections.Generic.IEnumerable`1[T] methodList, System.String methodName, System.Int32[] parameterTypeTokens, System.Type[] genericTypeArguments, System.Boolean exactArgumentTypes, System.Boolean throwIfNotFound) [0x00267] in <cef3f13c8ccf43e099826c1e36a2d61c>:0 
  at LiveSharp.Runtime.IL.MethodMetadata.DeserializeMembers (System.Collections.Generic.IEnumerable`1[T] memberElements) [0x003c8] in <cef3f13c8ccf43e099826c1e36a2d61c>:0 
  at LiveSharp.Runtime.IL.MethodMetadata..ctor (LiveSharp.Runtime.IL.TypeMetadata typeMetadata, System.Xml.Linq.XElement methodElement, LiveSharp.Runtime.Virtual.VirtualAssembly virtualAssembly, LiveSharp.ILogger logger) [0x0014b] in <cef3f13c8ccf43e099826c1e36a2d61c>:0 
  at LiveSharp.Runtime.IL.DocumentMetadata..ctor (System.Xml.Linq.XElement documentElement, LiveSharp.Runtime.Virtual.VirtualAssembly virtualAssembly, LiveSharp.ILogger logger, System.Func`2[T,TResult] methodFilter) [0x0016a] in <cef3f13c8ccf43e099826c1e36a2d61c>:0 
  at LiveSharp.Runtime.LiveSharpRuntime.UpdateDocument (System.Xml.Linq.XElement element, System.Func`2[T,TResult] methodFilter) [0x00007] in <cef3f13c8ccf43e099826c1e36a2d61c>:0 
  at LiveSharp.Runtime.LiveSharpRuntime.LiveSharpMessageReceived (System.String messageContent, System.Byte contentType, System.Int32 groupId) [0x00025] in <cef3f13c8ccf43e099826c1e36a2d61c>:0

**Comment by ionoy** [comment]
Can you post the definition of the `Define` method? Is there anything unusual about it? Does it work if you comment out the part that uses `Define`?

Thanks!

**Comment by chrisofthecoffee** [comment]
Hi, the only call to something called 'Define' is 6 versions of the below, creating grid definitions, I don't have a function called Define.

![image](https://user-images.githubusercontent.com/17450109/84150161-0ee51f80-aa94-11ea-9b49-8d134edaa64c.png)

**Comment by chrisofthecoffee** [comment]
This seems worthy of mention... 
![image](https://user-images.githubusercontent.com/17450109/84222161-8012ea00-ab09-11ea-826b-c73b6a9f5ef0.png)

**Comment by ionoy** [comment]
Please try the updated LiveSharp package (1.5.27). I have fixed the `Define` issue.

**Comment by chrisofthecoffee** [comment]
Ok thanks, I updated from 1.5.25 to 1.5.27 and now when I start/deploy the server window stays on the 'You can start the application now' panel and doesn't switch to the runtime panels. Un/re-installed client and server, rebooted, rebuilt, same.

Looking in the logs I can't see any errors, the below seems to say the server and client have said hello; 

log file...
18:42:13 client connected: 192.168.1.15:51524
18:42:14 Client 192.168.1.15:51524 joined group 1
18:42:14 Client 192.168.1.15:51524 joined group 4
18:42:14 (runtime) LiveSharp Server connected

output window...
[0:] livesharp: Connected to 192.168.1.15:50540
[0:] livesharp: LiveSharp Server connected

...so I don't understand why the server display isn't switching / watches not being set etc. - that worked fine half an hour ago on 1.5.25, any ideas / diags I can send ?

I'm super-happy to do all I can to help work out what's wrong, I'm well-invested in doing so having spent the last few days recoding XAML pages to C# as the new way forward with LiveSharp - if LiveSharp gives me the hot reload I'm giving up with switching then I'll gladly register, if it works it'll be fantastic but I really need to be making some progress soon and having to constantly rebuild for the smallest change is heavy going !

**Comment by chrisofthecoffee** [comment]
All the above is working now, lets close this epic - thanks for all your help.
