### ISSUE TITLE
KeyNotFound Exception

### ISSUE THREAD

**Issue by jh-webton** [OYIon/LiveSharp#74]
I'm upgraded to the latest server software & nuget package.
The server info screen says: License: Valid until vrijdag 19 juni 2020

After recieving the following exception the program stops working
`livesharp: error: System.Collections.Generic.KeyNotFoundException: The given key '7' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiveSharp.Runtime.IL.DocumentMetadata.<>c__DisplayClass16_0.<DeserializeTypes>b__2(Int32 t)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at LiveSharp.Runtime.IL.DocumentMetadata.DeserializeTypes(XElement[] types)
   at LiveSharp.Runtime.IL.DocumentMetadata..ctor(XElement documentElement, VirtualAssembly virtualAssembly, ILogger logger, Func`2 methodFilter)
   at LiveSharp.Runtime.LiveSharpRuntime.UpdateDocument(XElement element, Func`2 methodFilter)
   at LiveSharp.Runtime.LiveSharpRuntime.LiveSharpMessageReceived(String messageContent, Byte contentType, Int32 groupId)
The thread 0xbb18 has exited with code 0 (0x0).`

The exception is shown in Visual Studio 2019 output window. Don't see any messages in the server application.

**Comment by ionoy** [comment]
Do you have a code sample I could use to reproduce the issue?

**Comment by jh-webton** [comment]
First change I make it works, second I get the exception
Can't find the reason. I got the same exception in razor pages without the Telerik object.

`@page "/account/klanten"

@using Telerik.DataSource;

@layout AccountManagerLayout1
@inject NavigationManager NavManager

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">

<style>
    .k-grouping-header {
        display: none;
    }

    .k-grid tbody tr {
        line-height: 28px;
    }

    .k-grid tbody td {
        padding: 8px;
    }
</style>

<div class="h-screen flex overflow-hidden bg-gray-100">
    <div class="flex flex-col w-0 flex-1 overflow-hidden">
        <main class="flex-1 relative z-0 overflow-y-auto py-6 focus:outline-none" tabindex="0">
            <div class="ml-1 px-6">
                <div class="bg-white overflow-hidden sm:rounded-lg sm:shadow">
                    <div class="bg-white px-3 py-3 border-b border-gray-200 sm:px-6">
                        <div class="-ml-4 -mt-4 flex justify-between items-center flex-wrap sm:flex-no-wrap">
                            <div class="ml-4 mt-4">
                                <h3 class="text-lg leading-6 font-medium text-gray-900">
                                    Klanten
                                </h3>
                            </div>
                            <div class="mr-2 mt-3 flex-shrink-0">
                                <span class="inline-flex rounded-md shadow-sm">
                                    <button type="button" class="relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700" @onclick="btnAddCustomer">
                                        Voeg klant toe
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="mx-auto mt-4 px-6">
                        <div class="mb-3">
                            <dl>
                                <div class="sm:grid sm:grid-cols-8 sm:gap-4 ">
                                    <dt class="text-sm leading-5 font-medium text-gray-500 self-center">
                                        Klanten set
                                    </dt>
                                    <dd class="text-sm leading-5 text-gray-700 sm:mt-0 sm:col-span-1">
                                        <select id="filterCustomers" class="form-control filter-status bg-gray-200 border-t-0 border-l-0 border-r-0 border-b-4" name="select-status">
                                            <option value="2">Eigen klanten</option>
                                            <option value="1">Alle klanten</option>
                                        </select>
                                    </dd>
                                </div>

                                <div class="sm:grid sm:grid-cols-8 sm:gap-4 ">
                                    <dt class="mt-4 pt-1 text-sm leading-5 font-medium text-gray-500 self-center">
                                        Kalenderjaar
                                    </dt>
                                    <dd class="text-sm leading-5 text-gray-700 sm:mt-0 sm:col-span-2">
                                        <div class="sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start">
                                            <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
                                                <div class="hidden sm:block">
                                                    <div class="flex">
                                                        @{
                                                            int y = 0;
                                                            foreach (var year in years)
                                                            {
                                                                if (y == 3)
                                                                {
                                                                    if (!showAllYears)
                                                                    {
                                                                        <button type="button" class="mr-3 @btnInactive" @onclick="toggleOnShowAllYears">
                                                                            Alle
                                                                        </button>

                                                                        break;
                                                                    }
                                                                }

                                                                <button type="button" class="mr-3 @btnStyles[y]" @onclick="@(c => btnYear(@year))">
                                                                    @year
                                                                </button>

                                                                y++;
                                                            }
                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </dd>
                                </div>
                            </dl>
                        </div>

                        <div class="row mt-4 pt-3 mb-2">
                            <div class="col-md-12">
                                <div class="search-group">
                                    <input id="filterText" type="text" class="form-control input m-b-xs bg-gray-200 border-t-0 border-l-0 border-r-0 border-b-4 focus:shadow-outline-gray" autofocus placeholder="Zoek opdracht">
                                </div>
                            </div>
                        </div>
                        test
                        <div class="flex flex-col">
                            <div class="py-2 mb-3 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                                <div class="align-middle inline-block min-w-full overflow-hidden sm:rounded-lg border-b border-gray-200">
                                    <TelerikGrid Data=@GridData
                                                 Groupable="true"
                                                 OnStateInit="@((GridStateEventArgs<Models.Account.CustomerGridView> args) => OnStateInitHandler(args))"
                                                 Pageable=true PageSize=@PageSize
                                                 Sortable=true>
                                        <GridColumns>
                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.CustomerStatus) Title="Status" Width="85px">
                                                <Template>
                                                    @{
                                                        var customer = context as Models.Account.CustomerGridView;
                                                        if (customer.CustomerStatus == Enums.Status.Customer.Active)
                                                        {
                                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-200 text-green-800">
                                                                Actief
                                                            </span>
                                                        }
                                                        else if (customer.CustomerStatus == Enums.Status.Customer.Deactivated)
                                                        {
                                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-400 text-gray-800">
                                                                Inactief
                                                            </span>
                                                        }
                                                    }
                                                </Template>
                                            </GridColumn>
                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.CustomerName) Groupable="false" Width="1px">
                                                <Template>&nbsp;</Template>
                                                <GroupHeaderTemplate>
                                                    @{
                                                        <a href="@string.Format("/account/klanten/1")"><p class="text-indigo-600">@context.Value</p> </a>
                                                    }
                                                </GroupHeaderTemplate>
                                            </GridColumn>

                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.CompanyName) Title="Bedrijfsnaam" Groupable="false">
                                                <Template>
                                                    <a href="@string.Format("/account/bedrijven/{0}", (context as Models.Account.CustomerGridView).CompanyID)"> <p class="text-indigo-600">@string.Format("{0}", (context as Models.Account.CustomerGridView).CompanyName)</p> </a>
                                                </Template>
                                            </GridColumn>
                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.Period1Toegekend) Groupable="false" Title=@string.Format("{0}-1", activeYear) Width="75px">
                                                <Template>
                                                    <a href="@string.Format("/account/bedrijven/{0}/beschikkingen/{1}", ((context as Models.Account.CustomerGridView).CompanyID), activeYear)"> <p class="text-indigo-600">@string.Format("{0}", (context as Models.Account.CustomerGridView).Period1Toegekend)</p> </a>
                                                </Template>
                                            </GridColumn>
                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.Period1Realisatie) Groupable="false" Title=@string.Format("{0}-1", activeYear) Width="75px">
                                                <Template>
                                                    <a href="@string.Format("/account/bedrijven/{0}/realisaties/{1}", ((context as Models.Account.CustomerGridView).CompanyID), activeYear)"> <p class="text-indigo-600">@string.Format("{0}", (context as Models.Account.CustomerGridView).Period1Realisatie)</p> </a>
                                                </Template>
                                            </GridColumn>
                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.Period2Toegekend) Groupable="false" Title=@string.Format("{0}-2", activeYear) Width="75px">
                                                <Template>
                                                    <a href="@string.Format("/account/bedrijven/{0}/beschikkingen/{1}", ((context as Models.Account.CustomerGridView).CompanyID), activeYear)"> <p class="text-indigo-600">@string.Format("{0}", (context as Models.Account.CustomerGridView).Period2Toegekend)</p> </a>
                                                </Template>
                                            </GridColumn>
                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.Period2Realisatie) Groupable="false" Title="@string.Format("{0}-2", activeYear)" Width="75px">
                                                <Template>
                                                    <a href="@string.Format("/account/bedrijven/{0}/realisaties/{1}", ((context as Models.Account.CustomerGridView).CompanyID), activeYear)"> <p class="text-indigo-600">@string.Format("{0}", (context as Models.Account.CustomerGridView).Period2Realisatie)</p> </a>
                                                </Template>
                                            </GridColumn>
                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.Period3Toegekend) Groupable="false" Title=@string.Format("{0}-3", activeYear) Width="75px">
                                                <Template>
                                                    <a href="@string.Format("/account/bedrijven/{0}/beschikkingen/{1}", ((context as Models.Account.CustomerGridView).CompanyID), activeYear)"> <p class="text-indigo-600">@string.Format("{0}", (context as Models.Account.CustomerGridView).Period3Toegekend)</p> </a>
                                                </Template>
                                            </GridColumn>
                                            <GridColumn Field=@nameof(Models.Account.CustomerGridView.Period3Realisatie) Groupable="false" Title=@string.Format("{0}-3", activeYear) Width="75px">
                                                <Template>
                                                    <a href="@string.Format("/account/bedrijven/{0}/realisaties/{1}", ((context as Models.Account.CustomerGridView).CompanyID), activeYear)"> <p class="text-indigo-600">@string.Format("{0}", (context as Models.Account.CustomerGridView).Period3Realisatie)</p> </a>
                                                </Template>
                                            </GridColumn>
                                        </GridColumns>
                                    </TelerikGrid>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>


@code {
    #region Year buttons
    bool showAllYears = false;
    int activeYear = DateTime.Now.Year;
    int[] years = new int[] { 2020, 2019, 2018, 2017 };

    string btnActive = "relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-green focus:border-indigo-700 active:bg-indigo-700 transition duration-150 ease-in-out";
    string btnInactive = "relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-gray-600 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out";

    List<string> btnStyles;
    private void InitializeStyles()
    {
        btnStyles = new List<string>();

        foreach (var year in years)
        {
            btnStyles.Add(btnInactive);
        }
    }

    private void toggleOnShowAllYears()
    {
        showAllYears = true;
    }
    #endregion

    int PageSize = 6;

    public List<List<Models.Account.CustomerGridView>> AllYearsData { get; set; }
    public List<Models.Account.CustomerGridView> GridData { get; set; }
    public List<Models.Medew.Company> Companies { get; set; }
    public List<Models.Account.CustomerGridView> CompanyList { get; set; }

    async Task OnStateInitHandler(GridStateEventArgs<Models.Account.CustomerGridView> args)
    {
        GridState<Models.Account.CustomerGridView> desiredState = new GridState<Models.Account.CustomerGridView>()
        {
            GroupDescriptors = new List<GroupDescriptor>()
    {
                new GroupDescriptor()
                {
                    Member = "CustomerName",
                    DisplayContent = "Klantnaam", // this is how to set the string for the group indicator
                    MemberType = typeof(string),
                    SortDirection = ListSortDirection.Descending
                }
            }
        };

        // this is how to pass the state object you generate to the grid in the OnStateInit event
        args.GridState = desiredState;
    }

    protected override void OnInitialized()
    {
        base.OnInitialized();

        InitializeStyles();

        InitializeDataSet();

        SetActiveButton(activeYear);
    }

    private void InitializeDataSet()
    {
        #region Companies
        Companies = new List<Models.Medew.Company>();
        Companies.Add(new Models.Medew.Company
        {
            CompanyID = 1,
            Name = "Jansen R&D BV",
        });
        Companies.Add(new Models.Medew.Company
        {
            CompanyID = 2,
            Name = "Jansen Beheer BV",
        });
        #endregion

        #region Companies
        CompanyList = new List<Models.Account.CustomerGridView>();
        #region 2020
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 1,
            CustomerName = "De Jansen Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 1,
            CompanyName = "Jansen R&D BV",
            Period1Realisatie = 1296,
            Period1Toegekend = 1000,
            Period2Realisatie = 92382,
            Period2Toegekend = 100000,
            Period3Realisatie = 9211,
            Period3Toegekend = 10000
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 1,
            CustomerName = "De Jansen Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 2,
            CompanyName = "Jansen Beheer BV",
            Period1Realisatie = 117,
            Period1Toegekend = 100,
            Period2Realisatie = 172,
            Period2Toegekend = 200,
            Period3Realisatie = 89,
            Period3Toegekend = 100
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 2,
            CustomerName = "Pietersen Groep",
            CustomerStatus = Enums.Status.Customer.Deactivated,
            CompanyID = 3,
            CompanyName = "Pieterson BV",
            Period1Realisatie = 95,
            Period1Toegekend = 100,
            Period2Realisatie = 123,
            Period2Toegekend = 100,
            Period3Realisatie = 99,
            Period3Toegekend = 200
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 2,
            CustomerName = "Pietersen Groep",
            CustomerStatus = Enums.Status.Customer.Deactivated,
            CompanyID = 4,
            CompanyName = "Pieterson Holding BV",
            Period1Realisatie = 481,
            Period1Toegekend = 500,
            Period2Realisatie = 349,
            Period2Toegekend = 400,
            Period3Realisatie = 1024,
            Period3Toegekend = 100
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 3,
            CustomerName = "DAN Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 5,
            CompanyName = "Dans R&D BV",
            Period1Realisatie = 940,
            Period1Toegekend = 1000,
            Period2Realisatie = 821,
            Period2Toegekend = 700,
            Period3Realisatie = 726,
            Period3Toegekend = 700
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 3,
            CustomerName = "Dan Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 6,
            CompanyName = "Dans Beheer BV",
            Period1Realisatie = 195,
            Period1Toegekend = 200,
            Period2Realisatie = 192,
            Period2Toegekend = 200,
            Period3Realisatie = 271,
            Period3Toegekend = 250
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 3,
            CustomerName = "Dan Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 7,
            CompanyName = "Dans Construction BV",
            Period1Realisatie = 75,
            Period1Toegekend = 100,
            Period2Realisatie = 153,
            Period2Toegekend = 300,
            Period3Realisatie = 762,
            Period3Toegekend = 900
        });
        #endregion
        #region 2019
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 1,
            CustomerName = "De Jansen Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 1,
            CompanyName = "Jansen R&D BV",
            Period1Realisatie = 95,
            Period1Toegekend = 125,
            Period2Realisatie = 127,
            Period2Toegekend = 100,
            Period3Realisatie = 194,
            Period3Toegekend = 200
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 1,
            CustomerName = "De Jansen Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 2,
            CompanyName = "Jansen Beheer BV",
            Period1Realisatie = 402,
            Period1Toegekend = 400,
            Period2Realisatie = 125,
            Period2Toegekend = 125,
            Period3Realisatie = 225,
            Period3Toegekend = 225
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 2,
            CustomerName = "Pietersen Groep",
            CustomerStatus = Enums.Status.Customer.Deactivated,
            CompanyID = 3,
            CompanyName = "Pieterson BV",
            Period1Realisatie = 102,
            Period1Toegekend = 100,
            Period2Realisatie = 210,
            Period2Toegekend = 200,
            Period3Realisatie = 150,
            Period3Toegekend = 150
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 2,
            CustomerName = "Pietersen Groep",
            CustomerStatus = Enums.Status.Customer.Deactivated,
            CompanyID = 4,
            CompanyName = "Pieterson Holding BV",
            Period1Realisatie = 114,
            Period1Toegekend = 115,
            Period2Realisatie = 201,
            Period2Toegekend = 210,
            Period3Realisatie = 105,
            Period3Toegekend = 100,
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 3,
            CustomerName = "DAN Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 5,
            CompanyName = "Dans R&D BV",
            Period1Realisatie = 174,
            Period1Toegekend = 150,
            Period2Realisatie = 105,
            Period2Toegekend = 95,
            Period3Realisatie = 120,
            Period3Toegekend = 125
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 3,
            CustomerName = "Dan Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 6,
            CompanyName = "Dans Beheer BV",
            Period1Realisatie = 231,
            Period1Toegekend = 230,
            Period2Realisatie = 120,
            Period2Toegekend = 120,
            Period3Realisatie = 285,
            Period3Toegekend = 280,
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 3,
            CustomerName = "Dan Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 7,
            CompanyName = "Dans Construction BV",
            Period1Realisatie = 271,
            Period1Toegekend = 270,
            Period2Realisatie = 157,
            Period2Toegekend = 150,
            Period3Realisatie = 276,
            Period3Toegekend = 280
        });
        #endregion
        #region 2018
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 1,
            CustomerName = "De Jansen Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 1,
            CompanyName = "Jansen R&D BV",
            Period1Realisatie = 256,
            Period1Toegekend = 260,
            Period2Realisatie = 132,
            Period2Toegekend = 130,
            Period3Realisatie = 100,
            Period3Toegekend = 100
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 2,
            CustomerName = "Pietersen Groep",
            CustomerStatus = Enums.Status.Customer.Deactivated,
            CompanyID = 3,
            CompanyName = "Pieterson BV",
            Period1Realisatie = 182,
            Period1Toegekend = 180,
            Period2Realisatie = 143,
            Period2Toegekend = 150,
            Period3Realisatie = 172,
            Period3Toegekend = 180
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 2,
            CustomerName = "Pietersen Groep",
            CustomerStatus = Enums.Status.Customer.Deactivated,
            CompanyID = 4,
            CompanyName = "Pieterson Holding BV",
            Period1Realisatie = 242,
            Period1Toegekend = 240,
            Period2Realisatie = 124,
            Period2Toegekend = 130,
            Period3Realisatie = 321,
            Period3Toegekend = 320,
        });
        #endregion
        #region 2017
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 1,
            CustomerName = "De Jansen Groep",
            CustomerStatus = Enums.Status.Customer.Active,
            CompanyID = 1,
            CompanyName = "Jansen R&D BV",
            Period1Realisatie = 122,
            Period1Toegekend = 125,
            Period2Realisatie = 156,
            Period2Toegekend = 150,
            Period3Realisatie = 184,
            Period3Toegekend = 180
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 2,
            CustomerName = "Pietersen Groep",
            CustomerStatus = Enums.Status.Customer.Deactivated,
            CompanyID = 3,
            CompanyName = "Pieterson BV",
            Period1Realisatie = 321,
            Period1Toegekend = 320,
            Period2Realisatie = 126,
            Period2Toegekend = 120,
            Period3Realisatie = 244,
            Period3Toegekend = 250
        });
        CompanyList.Add(new Models.Account.CustomerGridView
        {
            CustomerID = 2,
            CustomerName = "Pietersen Groep",
            CustomerStatus = Enums.Status.Customer.Deactivated,
            CompanyID = 4,
            CompanyName = "Pieterson Holding BV",
            Period1Realisatie = 184,
            Period1Toegekend = 190,
            Period2Realisatie = 173,
            Period2Toegekend = 170,
            Period3Realisatie = 121,
            Period3Toegekend = 120,
        });
        #endregion
        #endregion

        #region DataSet
        AllYearsData = new List<List<Models.Account.CustomerGridView>>();

        var year2020 = GetData(0, 5);
        var year2019 = GetData(5, 7);
        var year2018 = GetData(7, 10);
        var year2017 = GetData(10, 11);

        AllYearsData.Add(year2020);
        AllYearsData.Add(year2019);
        AllYearsData.Add(year2018);
        AllYearsData.Add(year2017);
        #endregion
    }

    private List<Models.Account.CustomerGridView> GetData(int fromIndex, int tillIndex)
    {
        var dataSet = new List<Models.Account.CustomerGridView>();

        for (int i = fromIndex; i < tillIndex; i++)
        {
            var dataPoint = new Models.Account.CustomerGridView
            {
                CustomerName = CompanyList[i].CustomerName,
                CustomerID = CompanyList[i].CustomerID,
                CustomerStatus = CompanyList[i].CustomerStatus,
                CompanyID = CompanyList[i].CompanyID,
                CompanyName = CompanyList[i].CompanyName,
                Period1Realisatie = CompanyList[i].Period1Realisatie,
                Period1Toegekend = CompanyList[i].Period1Toegekend,
                Period2Realisatie = CompanyList[i].Period2Realisatie,
                Period2Toegekend = CompanyList[i].Period2Toegekend,
                Period3Realisatie = CompanyList[i].Period3Realisatie,
                Period3Toegekend = CompanyList[i].Period3Toegekend
            };

            dataSet.Add(dataPoint);
        }

        return dataSet;
    }

    public TelerikGrid<Models.Account.CustomerGridView> Grid { get; set; }
    async Task SetGridSort()
    {
        GridState<Models.Account.CustomerGridView> desiredState = new GridState<Models.Account.CustomerGridView>()
        {
            SortDescriptors = new List<SortDescriptor>()
    {
                new SortDescriptor { Member = "CompanyName", SortDirection = ListSortDirection.Descending }
            }
        };

        await Grid.SetState(desiredState);
    }

    private void SetActiveButton(int year)
    {
        activeYear = year;

        SetAllButtonsToInactive();

        var index = GetIndex(year);
        btnStyles[index] = btnActive;

        SetGridData(year);
    }

    private void SetAllButtonsToInactive()
    {
        int i = 0;
        foreach (var year in years)
        {
            btnStyles[i] = btnInactive;
            i++;
        }
    }

    private void btnYear(int year)
    {
        SetActiveButton(year);
        SetGridData(year);
    }

    private int GetIndex(int year)
    {
        var index = Array.IndexOf(years, year);
        return index;
    }

    private void SetGridData(int year)
    {
        var index = GetIndex(year);
        GridData = AllYearsData[index];
    }

    private void btnAddCustomer()
    {
        NavManager.NavigateTo("/account/klanten/add");
    }
}
`

**Comment by ionoy** [comment]
Please see if it works with this NuGet package. Thanks!

[LiveSharp.1.5.24.zip](https://github.com/OYIon/LiveSharp/files/4745450/LiveSharp.1.5.24.zip)

**Comment by jh-webton** [comment]
No more exception but the page isn't updated anymore

**Comment by ionoy** [comment]
What if you manually reload it with F5? Do you see the updated version or the old one?

**Comment by jh-webton** [comment]
The old one, both with F5 and CTRL-F5

**Comment by ionoy** [comment]
Please check if there are any other messages in the logs or Output window. I have created a similar page to test your code and after 1.5.24 it updates fine.

**Comment by jh-webton** [comment]
Just tested it again and I get this message in the logs

14:15:31 (runtime) LiveSharp Server connected
14:15:32 client connected: 127.0.0.1:53073
14:15:32 Client 127.0.0.1:53073 joined group 7
14:15:32 Client 127.0.0.1:53073 joined group 6
14:15:32 Error: EndReceive failed
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text)
   at LiveSharp.ServerApp.HostServer.HandleMessage(ServerMessage message) in C:\Projects\LiveSharp\src\LiveSharp.ServerApp\HostServer.cs:line 112
   at LiveSharp.ServerApp.Network.LiveServer.MessageReceived(ServerMessage message, Client client) in C:\Projects\LiveSharp\src\LiveSharp.Server\Network\LiveServer.cs:line 108
   at LiveProjectCommon.Server.LiveHost.Parser_MessageParsed(Object sender, ParserEventArgs`1 args) in C:\Projects\LiveSharp\src\LiveSharp.Server\Network\LiveHost.cs:line 79
   at LiveSharp.ServerClient.ParserBase`1.RaiseMessageReceived(TMessage message, Object payload) in C:\Projects\LiveSharp\src\LiveSharp.ServerClient\ParserBase.cs:line 33
   at LiveSharp.ServerClient.MessageParser.Feed(Byte b) in C:\Projects\LiveSharp\src\LiveSharp.ServerClient\MessageParser.cs:line 107
   at LiveSharp.ServerClient.ParserBase`1.Feed(Byte[] buffer, Int32 bytesRead) in C:\Projects\LiveSharp\src\LiveSharp.ServerClient\ParserBase.cs:line 20
   at LiveProjectCommon.Server.LiveHost.EndReceive(IAsyncResult ar) in C:\Projects\LiveSharp\src\LiveSharp.Server\Network\LiveHost.cs:line 112
14:15:32 client disconnected: 127.0.0.1:53073

**Comment by ionoy** [comment]
[LiveSharp.1.5.25.zip](https://github.com/OYIon/LiveSharp/files/4745876/LiveSharp.1.5.25.zip)

This should work

**Comment by jh-webton** [comment]
@ionoy, perfect. Works like a charm and I don't see any error messages in the logs
