### ISSUE TITLE
Low priority suggestion : Keep display of Log/Debugger/other panes visible

### ISSUE THREAD

**Issue by chrisofthecoffee** [OYIon/LiveSharp#75]
Currently the server component resets to the 'You can start the application now' display when the application is stopped.

This is handy on initial setting up and troubleshooting but once it all works fine it'd be better to keep the runtime displays visible by default, with a button or suchlike to display the help/setup page if it's wanted.

**Comment by ionoy** [comment]
This seems to be resolved with 1.6.x.x, right?

**Comment by chrisofthecoffee** [comment]
Yep, agreed - the other displays make more sense as-is.

Having said that, if the inspector and debugger could auto-scroll when the insertion point/carat is at the end that'd be cool, let's close this one off though.
