### ISSUE TITLE
Order still 'Processing' after 12 Hours!

### ISSUE THREAD

**Issue by neo210211** [OYIon/LiveSharp#76]
It's been more than 12 hours since I paid for my subscription. The order remains **_Processing_**!

![image](https://user-images.githubusercontent.com/2405580/84954166-c8736e80-b0ec-11ea-913f-8a488e05b20b.png)

**Comment by ionoy** [comment]
Hello @neo210211 

You can use your account as soon as you made the order. No need to wait for me to "Complete" it.

Sorry for the confusion!
