### ISSUE TITLE
Change in 3rd-Party Component Skips Update in Browser

### ISSUE THREAD

**Issue by warappa** [OYIon/LiveSharp#79]
While testing I noticed, that sometimes the browser won't update when I change a third-party component (like the caption of a MatBlazor MatButton in my case). When I change a built-in Button next to it, then both, the Button and the MatButton, are updated. So the change was actually compiled, just not published. I notice a "Type not found" exception which may be related to this.

### Repo
https://github.com/warappa/RepoLiveSharpUpdateFailsWithMatBlazor

#### Steps
1. Open /counter page in browser
2. Open Counter.razor in Visual Studio
3. Change `Change me` in `MatButton` to something else: _no_ browser update, but exception with message `Type not found` in output window
4. Change `Click me` in `button` to something else: browser updates - including the change from step 3

**Comment by ionoy** [comment]
Hi @warappa !

I was able to reproduce the issue, thanks! Can you try the following NuGet package?

[LiveSharp.1.5.53.zip](https://github.com/OYIon/LiveSharp/files/4946955/LiveSharp.1.5.53.zip)

**Comment by warappa** [comment]
It works! 👍

Thank you for the fast fix!
