### ISSUE TITLE
[Xamarin] Binding Count property not found on ObservableRangeCollection

### ISSUE THREAD

**Issue by YZahringer** [OYIon/LiveSharp#89]
### Description
I get an error on binding to the `Count` property of [MvvmHelpers.ObservableRangeCollection](https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/ObservableRangeCollection.cs):
> Binding: 'Count' property not found on 'MvvmHelpers.ObservableRangeCollection`1[System.String]', target property: 'Xamarin.Forms.Label.Text'

I make binding to a `Label.Text` and the label is not displayed. If I remove the `LiveSharp` package reference from the project, the label is displayed and binding works. I understand that `LiveSharp` may have problems on some views, but it should not alter the rendering of the application in my opinion.

No error when I use `System.Collections.ObjectModel.ObservableCollection`.

### Basic Information
- Version with issue: 1.5.75
- IDE: VS 16.7.2
- Xamarin.Forms: 4.8.0.1269

### Reproduction Link
https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/livesharp-observableRangeCollection

**Comment by ionoy** [comment]
Sorry for the late reply! The issue will be fixed in the next update, which will be published this week.

**Comment by ionoy** [comment]
@YZahringer new version should be published by now

**Comment by YZahringer** [comment]
@ionoy I confirm, I checked on multiple apps without any problem. Thank you 👍
