### ISSUE TITLE
No connection possible ('all of a sudden')

### ISSUE THREAD

**Issue by ChristianWeyer** [OYIon/LiveSharp#93]
Hm... somehow, LiveSharp no longer works as the client lib cannot connect to the server:

`polyfills.js:1 POST https://localhost.livesharp.net:30539/livesharp/negotiate?negotiateVersion=1 net::ERR_NAME_NOT_RESOLVED
`
![LiveSharp_Error](https://user-images.githubusercontent.com/888718/95360937-640f3180-08cc-11eb-82a2-3ba7ba351684.gif)

Any idea what could be wrong here?

**Comment by ionoy** [comment]
Seems like a DNS issue to me. Can you try `ping localhost.livesharp.net` to see what it resolves to?

**Comment by ChristianWeyer** [comment]
```
ping localhost.livesharp.net
Ping request could not find host localhost.livesharp.net. Please check the name and try again.
```

**Comment by ionoy** [comment]
Weird. What if you do `ipconfig /flushdns`?

**Comment by ChristianWeyer** [comment]
The same.

**Comment by ionoy** [comment]
You can also try temporarily changing your DNS to Google 8.8.8.8 or Cloudflare 1.1.1.1 to see if they resolve correctly.

**Comment by ChristianWeyer** [comment]
Did that, rebooted the machine. Started livesharp server. Then it works. Hmmm...

**Comment by ionoy** [comment]
Someone already reported a similar issue, but it seems like it just appears randomly, and I have no idea how to fix that. For some reason, Windows just "forgets" the DNS record for localhost.livesharp.net sometimes. Anyway, I'm closing this issue. Thank you for reporting it in the first place, maybe it will help someone if it happens again.
