### ISSUE TITLE
[Bug] iOS Requests to connect to local network devices even with LIVESHARP_DISABLE

### ISSUE THREAD

**Issue by DanGould** [OYIon/LiveSharp#95]
From Gitter Oct 6
"@ionoy @/all FYI iOS diplays a permission request on new install of Xamarin Forms app “would like to find and connect to devices on your local network”, this is because live sharp connects to localhost as we know, but EVEN when adding “LIVESHARP_DISABLE” to the configuration that I was building against, the app locally deployed to physical device still displays this, the only way I got rid of this permission request was to uninstall Livesharp Nuget package then release…. Not a big problem as I can create a release branch for my releases without LiveSharp, but just wanted to let you know"

I am experiencing [this problem in my app](https://github.com/chaincase-app/chaincase/issues/81) as well. Removing LiveSharp fixes the issue.

**Comment by ionoy** [comment]
Hello @DanGould 

Can you open the compiled assembly (netstandard one) in ilspy or a similar tool to check if there is any LiveSharp initialization code  in the `App` constructor?

**Comment by DanGould** [comment]
feelin like a derp for opening this and taking your attention when I think the issue was i did not LIVESHARP_DISABLE all of the projects involved

**Comment by ionoy** [comment]
No problem!
