### ISSUE TITLE
LiveSharp softlock

### ISSUE THREAD

**Issue by Flaflo** [OYIon/LiveSharp#99]
We have a project using MudBlazor and its dialogs, if we add components to the dialog and do a hot-reload, we are greeted with this in the log:
```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/livesharp'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 14907.668ms 101
```

after that LiveSharp stops hotreloading and we have to restart the project.

We set up a repository that has an example for this case, we would invite you to this private repo so you could investigate.

Thanks.

**Comment by ionoy** [comment]
Thanks for the report!

Can you PM me on Gitter https://gitter.im/LiveSharp/Lobby @ionoy so we could arrange that?

**Comment by Flaflo** [comment]
Good news! As of the newest version this seems to be fixed!
